In [ ]:
# 구글드라이브 연동
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 구글드라이브 연동 확인
!ls

drive  sample_data


In [11]:
# 디렉토리 지정
%cd /content/drive/My Drive/Colab/data

/content/drive/My Drive/data


In [13]:
# 디렉토리 내 전체 파일의 목록
%ls

links.csv   new_data.txt   ratings.csv  test.txt
movies.csv  new_data.xlsx  tags.csv


## **행렬 분해 기반 추천 시스템 : 특정 영화와 비슷한 영화 추천**

In [14]:
import pandas as pd
# 데이터 가져오기
rating_data = pd.read_csv('./ratings.csv')
movie_data = pd.read_csv('./movies.csv')
# 데이터 출력
rating_data.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [15]:
movie_data.head()

movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [16]:
print(rating_data.shape)
print(movie_data.shape)

(100004, 4)
(9125, 3)


In [17]:
# 불필요한 데이터 제거 
# (axis=0은 행을, axis=1은 열을 삭제하란 의미 / inplace=True는 drop을 적용한 데이터를 반환)
rating_data.drop('timestamp', axis=1, inplace = True)
rating_data.head()
movie_data.drop('genres', axis=1, inplace = True)
movie_data.head()

movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [18]:
# 두 데이터를 공통 컬럼인 movieId로 merge
user_movie_data = pd.merge(rating_data, movie_data, on='movieId')
user_movie_data.head()

userId  movieId  rating                   title
0       1       31     2.5  Dangerous Minds (1995)
1       7       31     3.0  Dangerous Minds (1995)
2      31       31     4.0  Dangerous Minds (1995)
3      32       31     4.0  Dangerous Minds (1995)
4      36       31     3.0  Dangerous Minds (1995)

In [19]:
# pandas의 pivot table을 활용해 (userId X title) 매트릭스 생성
user_movie_rating = user_movie_data.pivot_table('rating', index='userId', columns='title').fillna(0)
user_movie_rating.head()

title   "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
userId                                    ...                     
1                                    0.0  ...                  0.0
2                                    0.0  ...                  0.0
3                                    0.0  ...                  0.0
4                                    0.0  ...                  0.0
5                                    0.0  ...                  0.0

[5 rows x 9064 columns]

In [20]:
# numpy의 .T를 사용해 pivot table을 transpose(전치)함
movie_user_rating = user_movie_rating.values.T
# numpy.ndarray는 head()로 출력할 수 없으므로, 아래와 같은 방식으로 데이터의 일부를 출력함
head = movie_user_rating[:2]
print(head)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
# 행렬 분해 방법 중 하나인 '특이값 분해(SVD)'를 사용하여 (M X N) 크기의 행렬을 분해
# 매개변수 n_components는 latent 값을 의미함
from sklearn.decomposition import TruncatedSVD
SVD = TruncatedSVD(n_components=12)
matrix = SVD.fit_transform(movie_user_rating)
matrix[0]

array([ 0.01227491,  0.00250767,  0.01554899, -0.03397481, -0.01444906,
        0.00360247, -0.00238239,  0.04476259, -0.01614862, -0.02206115,
        0.01136405, -0.00964372])

In [24]:
# 피어슨 상관계수 계산
import numpy as np
corr = np.corrcoef(matrix)
corr.shape

(9064, 9064)

In [32]:
# 상관계수를 이용해서 'Guardians of the Galaxy'와 관련성이 높은 영화를 출력 (=상관계수가 높은 영화 출력)
movie_title = user_movie_rating.columns
movie_title_list = list(movie_title)
coffey_hands = movie_title_list.index("Guardians of the Galaxy (2014)")

In [36]:
corr_coffey_hands = corr[coffey_hands]
list(movie_title[(corr_coffey_hands >= 0.9)])[:10]

['10,000 BC (2008)',
 '2 Guns (2013)',
 '2012 (2009)',
 '300: Rise of an Empire (2014)',
 'Abduction (2011)',
 'Adjustment Bureau, The (2011)',
 'Adventures of Tintin, The (2011)',
 'Alice in Wonderland (2010)',
 'Amazing Spider-Man, The (2012)',
 'Angels & Demons (2009)']